import Erdos848.GeneratedTailSupportProfileCoverage.K2Certificate
import Erdos848.GeneratedTailSupportProfileCoverage.K3Certificate
import Erdos848.GeneratedTailSupportProfileCoverage.K4Certificate
import Erdos848.GeneratedTailSupportProfileCoverage.K6Certificate
