import Erdos848.GeneratedTruncatedDiagonalTwoHundredMillionAtoms.ProjectionAggregateLevel01Block0042
import Erdos848.GeneratedTruncatedDiagonalTwoHundredMillionAtoms.ProjectionAggregateLevel01Block0043

namespace Erdos848.GeneratedTruncatedDiagonalTwoHundredMillionAtoms

set_option maxRecDepth 1000000
set_option maxHeartbeats 0

def projectionAggregateLevel02Block0021 :=
  IndexedMarkerData.truncatedAtomProjectionRangeAppend projectionAggregateLevel01Block0042 projectionAggregateLevel01Block0043

end Erdos848.GeneratedTruncatedDiagonalTwoHundredMillionAtoms
